name: CI Workflow

on:
  pull_request:
    types: [opened, reopened]
    branches: [develop, main]
    paths-ignore: 
      - README.md
  workflow_dispatch:

jobs:
  tests:
    name: Execução de Testes com Pytest
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup do Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Teste de Versão
        run: python --version

      - name: Instalação de Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar Testes Unitários
        run: pytest tests/ -v
  
  security_analysis:
    # script baseado na documentação do semgrep
    name: Análise de Segurança com Semgrep
    permissions: 
      contents: read

    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep
    
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout do código
        uses: actions/checkout@v7
      
      - name: Checagem de Segurança com Semgrep
        run: semgrep scan --config p/python